doctrine_migrations:
  migrations_paths:
    'App\Shared\Infrastructure\Doctrine\Migrations': '%kernel.project_dir%/src/Shared/Infrastructure/Doctrine/Migrations'
    'App\User\Infrastructure\Doctrine\Migrations': '%kernel.project_dir%/src/User/Infrastructure/Doctrine/Migrations'
