parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  _instanceof:
    App\Shared\Domain\UseCase\UseCaseHandler:
      tags: [ 'messenger.message_handler' ]

  ## Shared
  App\Shared\Application\:
    resource: '../src/Shared/Application'
  App\Shared\Domain\:
    resource: '../src/Shared/Domain'
  App\Shared\Infrastructure\:
    resource: '../src/Shared/Infrastructure'

  ## User
  App\User\Application\:
    resource: '../src/User/Application'
  App\User\Domain\:
    resource: '../src/User/Domain'
  App\User\Infrastructure\:
    resource: '../src/User/Infrastructure'

